# -*- coding: utf-8 -*-
"""Gold.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/118c7VJOsS3w7V9W3nnRl3rIevNCXK72L
"""

import os #للتعامل مع الملفات و المسارات داخل البرنامج osاستدعاء مكتبة
import pandas as pd   # استدعاء المكتبة لقراءة البيانات و معالجتها

PATH = ("gld_price_data.csv")

rd = pd.read_csv(PATH , sep=";") # قراءة ملف البيانات من نوع csv و تحويله لجداول
print(rd.shape) # طباعة عدد الصفوف والأعمدة داخل ملف البيانات
print(rd.columns.tolist()) #عرض اسماء الأعمدة الموجودة في الملف
rd.head() #عرض اول 5 صفوف للتأكد من قراءة البيانات بشكل صحيح

import os

data_dirc = "GOLD"
print(os.listdir(data_dirc))

target_colum = "EUR/USD"  # الهدف هو عمود الاسعار ليتنبأ بها

rd = rd.dropna(subset=[target_colum]).drop_duplicates().copy() # لحذف الصفوف الفارغة


X = rd.drop(columns=[target_colum]) # حذف العمود الهدف من البيانات
y = rd[target_colum] # تخزين العمود المستهدف بهذا المتغير

print("X columns:", X.columns.tolist())

display(rd.head()) # عرض البيانات على شكل جدول

if "date" in X.columns: # لتقسيم عامود التاريخ الى اربعة اقسام ليسهل عملية التنبؤ
    X["date"] = pd.to_datetime(X["date"], errors="coerce")
    X["Year"] = X["date"].dt.year
    X["Month"] = X["date"].dt.month
    X["Day"] = X["date"].dt.day
    X = X.drop(columns=["date"]) # حذف عامود date

print("After date features:", X.columns.tolist()) # عرض  اسماء الاعمدة داخل البيانات بعد تقسيم العامود

from sklearn.model_selection import train_test_split # استدعاء دالة التقسيم ، لتقسيم البيانات الى جزء للتدريب و جزء للاختبار
from sklearn.compose import ColumnTransformer # لتطبيق معالجة مختلفة بحسب اخلاف الاعمدة
from sklearn.pipeline import Pipeline # للقيام بالخطوات على الترتيب
from sklearn.impute import SimpleImputer# لتعويض القيم الناقصة في البيانات

num_cols = X.select_dtypes(include=["int64","float64"]).columns.tolist() # تحديد الاعمدة التي تحتوي على ارقام و تخزينها في هذا المتغير
#
A_train, A_test, B_train, B_test = train_test_split( #تقسيم البيانات الى جزء للتدريب و جزء للإختبار
    X, y, test_size=0.2, random_state=42 # تحديد نسبة بيانات الاختبار للنموذج بنسبة 20% و بيانات الندريب بنسبة 80%  فقط
)
# لمعالجة الأعمدة الرقمية وتعويض القيم الناقصة بالمتوسط
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median"))
])
# تطبيق معالجة الأعدة الرقمية و تعويض القيم الناقصة
preprocess = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, num_cols)
    ],
    remainder="drop"
)

from sklearn.ensemble import HistGradientBoostingRegressor # استيراد نموذج regression للتنبؤ بالارقام
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score # استيراد ادوات لقياس اداء النموذج
import numpy as np # للتعامل مع العمليات الرياضية

AI = HistGradientBoostingRegressor(random_state=42)  # انشاء نموذج التنبؤ للتدرب على البيانات الرقمية
# معالجة البيانات ثم تدريب النموذج عليها
pipe = Pipeline(steps=[
    ("preprocess", preprocess),
    ("AI", AI)
])
#  تدريب النموذج على البيانات و تخزينها
pipe.fit(A_train, B_train)
pred = pipe.predict(A_test)

mae = mean_absolute_error(B_test, pred) # متوسط حجم الخطأ بين توقعات النموذج  و النتائج الحقيقية
rmse = np.sqrt(mean_squared_error(B_test, pred)) # حجم الخطأ للنموذج
r2 = r2_score(B_test, pred) # جودة النتائج المقدمة من النموذج

print("MAE :", mae)
print("RMSE:", rmse)
print("R2  :", r2)

import joblib #استدعاء المكتبة لحفظ الملفات و النموذج

AI_path ="GOLD_PRED.joblib" #GOLD_PRED حفظ النموذج باسم
joblib.dump(pipe, AI_path) #  حفظ النموذج لاستخدامه لاحقا
print("Saved:", AI_path)

# لاستدعائها فيما بعد لانشاء واجهة مستخدم gradio تثبيت مكتب
import gradio as gr # لانشاء واجهة مستخدم  gradio  استدعاء مكتبة
import joblib  # لتحميل النموذج التي تم حفظها سابقا    joblib استدعاء مكتبة
import pandas as pd

pipe = joblib.load("GOLD_PRED.joblib") # تحميل النموذج
# تجهيز الواجهة لتمكين المستخدم من ادخال القيم
theme = gr.themes.Soft( # gradio استخدام ثيم جاهز من مكتبة
    primary_hue="blue",  #  اللون الاساسي للازرار و خلفية الاسماء
    secondary_hue="amber" )
inputs = []
for col in X.columns:
        inputs.append(gr.Number(label=col, value=0 , interactive=True ,minimum=0,maximum=10000))
# تعريف دالة التنبؤ التي تستقبل المدخلات من المستخدم
def prediction(*vals):
    row = {col: vals[i] for i, col in enumerate(X.columns)}
    sample = pd.DataFrame([row])

    # التأكد من كل الأعمدة تحتوي على ارقام
    for c in num_cols:
        sample[c] = pd.to_numeric(sample[c], errors="coerce")

    return float(pipe.predict(sample)[0])

app = gr.Interface( # إنشاء واجهة المستخدم
    fn=prediction,  # ربط الواجهة بدالة التنبؤ
    inputs=inputs, #  المدخلات
    outputs=gr.Number(label="Predicted sales GOLD"), # تحديد شكل و اسم الناتج
    title="AI GOLD PRICE" # العنوان
    theme=theme
)
app.launch()

